apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: dapp
  name: dapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dapp
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/lab4-default: "true"
        io.kompose.service: dapp
    spec:
      containers:
        - image: schadokar/eth-server:1.0.0
          name: dapp
          ports:
            - containerPort: 4000
              hostPort: 4000
              protocol: TCP
          env:
            - name: NODE_PORT
              valueFrom:
                configMapKeyRef:
                  name: node-app-config
                  key: NODE_PORT
          resources:
            requests:
              memory: 128Mi
              cpu: 500m
            limits:
              memory: 64Mi
              cpu: 250m
      restartPolicy: Always
